[toolchain]
channel = "stable"
components = ["clippy", "rustfmt"]
targets = [
  "wasm32-wasip2",
  "aarch64-apple-ios",
  "aarch64-apple-ios-sim",
  "x86_64-apple-ios",
  "aarch64-linux-android",
  "armv7-linux-androideabi",
  "i686-linux-android",
  "x86_64-linux-android",
]
profile = "minimal"
